/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DlocalBalance model module.
 * @module Model/DlocalBalance
 * @version 1.37.9
 */
class DlocalBalance {
    /**
     * Constructs a new <code>DlocalBalance</code>.
     * @alias module:Model/DlocalBalance
     */
    constructor() { 
        
        DlocalBalance.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DlocalBalance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/DlocalBalance} obj Optional instance to populate.
     * @return {module:Model/DlocalBalance} The populated <code>DlocalBalance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DlocalBalance();

            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('available_balance')) {
                obj['available_balance'] = ApiClient.convertToType(data['available_balance'], 'Number');
            }
            if (data.hasOwnProperty('previous_day_closing_balance')) {
                obj['previous_day_closing_balance'] = ApiClient.convertToType(data['previous_day_closing_balance'], 'Number');
            }
            if (data.hasOwnProperty('current_balance_date')) {
                obj['current_balance_date'] = ApiClient.convertToType(data['current_balance_date'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The currency of this balance
 * @member {String} currency
 */
DlocalBalance.prototype['currency'] = undefined;

/**
 * The available balance for the given currency
 * @member {Number} available_balance
 */
DlocalBalance.prototype['available_balance'] = undefined;

/**
 * The balance at end of previous day
 * @member {Number} previous_day_closing_balance
 */
DlocalBalance.prototype['previous_day_closing_balance'] = undefined;

/**
 * Current date
 * @member {String} current_balance_date
 */
DlocalBalance.prototype['current_balance_date'] = undefined;






export default DlocalBalance;

