/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Entity from './Entity';

/**
 * The EntityListResponse model module.
 * @module Model/EntityListResponse
 * @version 1.25.0
 */
class EntityListResponse {
    /**
     * Constructs a new <code>EntityListResponse</code>.
     * Attributes needed to calculate the risk scores for the automated fields
     * @alias module:Model/EntityListResponse
     */
    constructor() { 
        
        EntityListResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntityListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/EntityListResponse} obj Optional instance to populate.
     * @return {module:Model/EntityListResponse} The populated <code>EntityListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityListResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Entity]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:Model/Entity>} data
 */
EntityListResponse.prototype['data'] = undefined;






export default EntityListResponse;

