/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MandateStatus from './MandateStatus';

/**
 * The Mandate model module.
 * @module Model/Mandate
 * @version 1.37.9
 */
class Mandate {
    /**
     * Constructs a new <code>Mandate</code>.
     * A Mandate authorises payouts to a Recipient. Mandates are issued per calendar year and must be in a &#x60;signed&#x60; (or &#x60;bypassed&#x60;) state before the linked Recipient can receive a payout.
     * @alias module:Model/Mandate
     */
    constructor() { 
        
        Mandate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Mandate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/Mandate} obj Optional instance to populate.
     * @return {module:Model/Mandate} The populated <code>Mandate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Mandate();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = MandateStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('type_id')) {
                obj['type_id'] = ApiClient.convertToType(data['type_id'], 'Number');
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
            if (data.hasOwnProperty('signed_at')) {
                obj['signed_at'] = ApiClient.convertToType(data['signed_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * ID of the mandate
 * @member {String} id
 */
Mandate.prototype['id'] = undefined;

/**
 * @member {module:Model/MandateStatus} status
 */
Mandate.prototype['status'] = undefined;

/**
 * Numeric beneficiary type identifier. Identifies whether the mandate was issued for a natural person, sole proprietor, partnership, company, etc.
 * @member {Number} type_id
 */
Mandate.prototype['type_id'] = undefined;

/**
 * Human-readable reference assigned to the mandate at creation.
 * @member {String} reference
 */
Mandate.prototype['reference'] = undefined;

/**
 * Timestamp when the mandate transitioned to `signed`. `null` for mandates that are pending, notified, failed, or bypassed.
 * @member {Date} signed_at
 */
Mandate.prototype['signed_at'] = undefined;

/**
 * Timestamp when the mandate was created.
 * @member {Date} created_at
 */
Mandate.prototype['created_at'] = undefined;

/**
 * Timestamp when the mandate was last updated.
 * @member {Date} updated_at
 */
Mandate.prototype['updated_at'] = undefined;






export default Mandate;

