/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MandateStatus.
* @enum {}
* @readonly
*/
export default class MandateStatus {
    
        /**
         * value: "pending"
         * @const
         */
        "pending" = "pending";

    
        /**
         * value: "notified"
         * @const
         */
        "notified" = "notified";

    
        /**
         * value: "signed"
         * @const
         */
        "signed" = "signed";

    
        /**
         * value: "failed"
         * @const
         */
        "failed" = "failed";

    
        /**
         * value: "bypassed"
         * @const
         */
        "bypassed" = "bypassed";

    

    /**
    * Returns a <code>MandateStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:Model/MandateStatus} The enum <code>MandateStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

