/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OpenCorporatesSearch from './OpenCorporatesSearch';

/**
 * The OpenCorporatesSearchRequest model module.
 * @module Model/OpenCorporatesSearchRequest
 * @version 1.24.0
 */
class OpenCorporatesSearchRequest {
    /**
     * Constructs a new <code>OpenCorporatesSearchRequest</code>.
     * @alias module:Model/OpenCorporatesSearchRequest
     */
    constructor() { 
        
        OpenCorporatesSearchRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OpenCorporatesSearchRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/OpenCorporatesSearchRequest} obj Optional instance to populate.
     * @return {module:Model/OpenCorporatesSearchRequest} The populated <code>OpenCorporatesSearchRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OpenCorporatesSearchRequest();

            if (data.hasOwnProperty('search')) {
                obj['search'] = OpenCorporatesSearch.constructFromObject(data['search']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Model/OpenCorporatesSearch} search
 */
OpenCorporatesSearchRequest.prototype['search'] = undefined;






export default OpenCorporatesSearchRequest;

