/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OpenCorporatesSearch from './OpenCorporatesSearch';
import Sender from './Sender';
import ValidationErrorDescription from './ValidationErrorDescription';

/**
 * The OpenCorporatesSenderUpdateResult model module.
 * @module Model/OpenCorporatesSenderUpdateResult
 * @version 1.25.0
 */
class OpenCorporatesSenderUpdateResult {
    /**
     * Constructs a new <code>OpenCorporatesSenderUpdateResult</code>.
     * @alias module:Model/OpenCorporatesSenderUpdateResult
     */
    constructor() { 
        
        OpenCorporatesSenderUpdateResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OpenCorporatesSenderUpdateResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/OpenCorporatesSenderUpdateResult} obj Optional instance to populate.
     * @return {module:Model/OpenCorporatesSenderUpdateResult} The populated <code>OpenCorporatesSenderUpdateResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OpenCorporatesSenderUpdateResult();

            if (data.hasOwnProperty('search')) {
                obj['search'] = OpenCorporatesSearch.constructFromObject(data['search']);
            }
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = Sender.constructFromObject(data['sender']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], {'String': [ValidationErrorDescription]});
            }
        }
        return obj;
    }


}

/**
 * @member {module:Model/OpenCorporatesSearch} search
 */
OpenCorporatesSenderUpdateResult.prototype['search'] = undefined;

/**
 * @member {module:Model/Sender} sender
 */
OpenCorporatesSenderUpdateResult.prototype['sender'] = undefined;

/**
 * The fields that have some problems and don't pass validation
 * @member {Object.<String, Array.<module:Model/ValidationErrorDescription>>} errors
 */
OpenCorporatesSenderUpdateResult.prototype['errors'] = undefined;






export default OpenCorporatesSenderUpdateResult;

