/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ValidationErrorDescription from './ValidationErrorDescription';

/**
 * The OpenCorporatesSearch model module.
 * @module Model/OpenCorporatesSearch
 * @version 1.25.0
 */
class OpenCorporatesSearch {
    /**
     * Constructs a new <code>OpenCorporatesSearch</code>.
     * @alias module:Model/OpenCorporatesSearch
     * @param country {String} Alpha2 code of the country that the company to be searched is registered in
     * @param registrationNumber {String} Registration number of the company to be searched
     */
    constructor(country, registrationNumber) { 
        
        OpenCorporatesSearch.initialize(this, country, registrationNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, country, registrationNumber) { 
        obj['country'] = country;
        obj['registration_number'] = registrationNumber;
    }

    /**
     * Constructs a <code>OpenCorporatesSearch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/OpenCorporatesSearch} obj Optional instance to populate.
     * @return {module:Model/OpenCorporatesSearch} The populated <code>OpenCorporatesSearch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OpenCorporatesSearch();

            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('registration_number')) {
                obj['registration_number'] = ApiClient.convertToType(data['registration_number'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], {'String': [ValidationErrorDescription]});
            }
        }
        return obj;
    }


}

/**
 * Alpha2 code of the country that the company to be searched is registered in
 * @member {String} country
 */
OpenCorporatesSearch.prototype['country'] = undefined;

/**
 * Registration number of the company to be searched
 * @member {String} registration_number
 */
OpenCorporatesSearch.prototype['registration_number'] = undefined;

/**
 * State/Province for countries that require it.
 * @member {String} state
 */
OpenCorporatesSearch.prototype['state'] = undefined;

/**
 * The company name that was returned from Open Corporates search
 * @member {String} name
 */
OpenCorporatesSearch.prototype['name'] = undefined;

/**
 * The fields that have some problems and don't pass validation
 * @member {Object.<String, Array.<module:Model/ValidationErrorDescription>>} errors
 */
OpenCorporatesSearch.prototype['errors'] = undefined;






export default OpenCorporatesSearch;

