/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OpenCorporatesSenderUpdate from './OpenCorporatesSenderUpdate';

/**
 * The OpenCorporatesSenderUpdateRequest model module.
 * @module Model/OpenCorporatesSenderUpdateRequest
 * @version 1.24.0
 */
class OpenCorporatesSenderUpdateRequest {
    /**
     * Constructs a new <code>OpenCorporatesSenderUpdateRequest</code>.
     * @alias module:Model/OpenCorporatesSenderUpdateRequest
     */
    constructor() { 
        
        OpenCorporatesSenderUpdateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OpenCorporatesSenderUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/OpenCorporatesSenderUpdateRequest} obj Optional instance to populate.
     * @return {module:Model/OpenCorporatesSenderUpdateRequest} The populated <code>OpenCorporatesSenderUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OpenCorporatesSenderUpdateRequest();

            if (data.hasOwnProperty('sender')) {
                obj['sender'] = OpenCorporatesSenderUpdate.constructFromObject(data['sender']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Model/OpenCorporatesSenderUpdate} sender
 */
OpenCorporatesSenderUpdateRequest.prototype['sender'] = undefined;






export default OpenCorporatesSenderUpdateRequest;

