/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PayoutMethodTransferReasonEnum from './PayoutMethodTransferReasonEnum';

/**
 * The PayoutMethodDetailsMADBank model module.
 * @module Model/PayoutMethodDetailsMADBank
 * @version 1.37.10
 */
class PayoutMethodDetailsMADBank {
    /**
     * Constructs a new <code>PayoutMethodDetailsMADBank</code>.
     * &#x60;&#x60;&#x60;JSON \&quot;details\&quot;: {   \&quot;first_name\&quot;: \&quot;First\&quot;,   \&quot;last_name\&quot;: \&quot;Last\&quot;,   \&quot;iban\&quot;: \&quot;007787001988877665431292\&quot;, // 24-char Moroccan IBAN   \&quot;street\&quot;: \&quot;1 Main Street\&quot;,   \&quot;transfer_reason\&quot;: \&quot;personal_account\&quot; } &#x60;&#x60;&#x60;
     * @alias module:Model/PayoutMethodDetailsMADBank
     * @param firstName {String} 
     * @param lastName {String} 
     * @param iban {String} 
     * @param street {String} 
     */
    constructor(firstName, lastName, iban, street) { 
        
        PayoutMethodDetailsMADBank.initialize(this, firstName, lastName, iban, street);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firstName, lastName, iban, street) { 
        obj['first_name'] = firstName;
        obj['last_name'] = lastName;
        obj['iban'] = iban;
        obj['street'] = street;
    }

    /**
     * Constructs a <code>PayoutMethodDetailsMADBank</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/PayoutMethodDetailsMADBank} obj Optional instance to populate.
     * @return {module:Model/PayoutMethodDetailsMADBank} The populated <code>PayoutMethodDetailsMADBank</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayoutMethodDetailsMADBank();

            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('iban')) {
                obj['iban'] = ApiClient.convertToType(data['iban'], 'String');
            }
            if (data.hasOwnProperty('street')) {
                obj['street'] = ApiClient.convertToType(data['street'], 'String');
            }
            if (data.hasOwnProperty('transfer_reason')) {
                obj['transfer_reason'] = PayoutMethodTransferReasonEnum.constructFromObject(data['transfer_reason']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} first_name
 */
PayoutMethodDetailsMADBank.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
PayoutMethodDetailsMADBank.prototype['last_name'] = undefined;

/**
 * @member {String} iban
 */
PayoutMethodDetailsMADBank.prototype['iban'] = undefined;

/**
 * @member {String} street
 */
PayoutMethodDetailsMADBank.prototype['street'] = undefined;

/**
 * @member {module:Model/PayoutMethodTransferReasonEnum} transfer_reason
 */
PayoutMethodDetailsMADBank.prototype['transfer_reason'] = undefined;






export default PayoutMethodDetailsMADBank;

