/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PayoutMethodBankAccountTypeEnum from './PayoutMethodBankAccountTypeEnum';
import PayoutMethodIdentityCardTypeEnum from './PayoutMethodIdentityCardTypeEnum';

/**
 * The PayoutMethodDetailsPENBank model module.
 * @module Model/PayoutMethodDetailsPENBank
 * @version 1.37.10
 */
class PayoutMethodDetailsPENBank {
    /**
     * Constructs a new <code>PayoutMethodDetailsPENBank</code>.
     * &#x60;&#x60;&#x60;JSON \&quot;details\&quot;: {   \&quot;first_name\&quot;: \&quot;Maria\&quot;,   \&quot;last_name\&quot;: \&quot;Lopez\&quot;,   \&quot;identity_card_type\&quot;: \&quot;DNI\&quot;, // DNI, RUC, CE (Carnet Extranjeria), PASS   \&quot;identity_card_id\&quot;: \&quot;12345678\&quot;,   \&quot;bank_code\&quot;: \&quot;002\&quot;,   \&quot;bank_account\&quot;: \&quot;00219300247595201411\&quot;, // 20-digit CCI   \&quot;bank_account_type\&quot;: \&quot;20\&quot; // 10&#x3D;Savings, 20&#x3D;Checking, 50&#x3D;Maestra } &#x60;&#x60;&#x60;
     * @alias module:Model/PayoutMethodDetailsPENBank
     * @param firstName {String} 
     * @param lastName {String} 
     * @param identityCardType {module:Model/PayoutMethodIdentityCardTypeEnum} 
     * @param identityCardId {String} 
     * @param bankCode {String} 
     * @param bankAccount {String} 
     * @param bankAccountType {module:Model/PayoutMethodBankAccountTypeEnum} 
     */
    constructor(firstName, lastName, identityCardType, identityCardId, bankCode, bankAccount, bankAccountType) { 
        
        PayoutMethodDetailsPENBank.initialize(this, firstName, lastName, identityCardType, identityCardId, bankCode, bankAccount, bankAccountType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firstName, lastName, identityCardType, identityCardId, bankCode, bankAccount, bankAccountType) { 
        obj['first_name'] = firstName;
        obj['last_name'] = lastName;
        obj['identity_card_type'] = identityCardType;
        obj['identity_card_id'] = identityCardId;
        obj['bank_code'] = bankCode;
        obj['bank_account'] = bankAccount;
        obj['bank_account_type'] = bankAccountType;
    }

    /**
     * Constructs a <code>PayoutMethodDetailsPENBank</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/PayoutMethodDetailsPENBank} obj Optional instance to populate.
     * @return {module:Model/PayoutMethodDetailsPENBank} The populated <code>PayoutMethodDetailsPENBank</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayoutMethodDetailsPENBank();

            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('identity_card_type')) {
                obj['identity_card_type'] = PayoutMethodIdentityCardTypeEnum.constructFromObject(data['identity_card_type']);
            }
            if (data.hasOwnProperty('identity_card_id')) {
                obj['identity_card_id'] = ApiClient.convertToType(data['identity_card_id'], 'String');
            }
            if (data.hasOwnProperty('bank_code')) {
                obj['bank_code'] = ApiClient.convertToType(data['bank_code'], 'String');
            }
            if (data.hasOwnProperty('bank_account')) {
                obj['bank_account'] = ApiClient.convertToType(data['bank_account'], 'String');
            }
            if (data.hasOwnProperty('bank_account_type')) {
                obj['bank_account_type'] = PayoutMethodBankAccountTypeEnum.constructFromObject(data['bank_account_type']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} first_name
 */
PayoutMethodDetailsPENBank.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
PayoutMethodDetailsPENBank.prototype['last_name'] = undefined;

/**
 * @member {module:Model/PayoutMethodIdentityCardTypeEnum} identity_card_type
 */
PayoutMethodDetailsPENBank.prototype['identity_card_type'] = undefined;

/**
 * @member {String} identity_card_id
 */
PayoutMethodDetailsPENBank.prototype['identity_card_id'] = undefined;

/**
 * @member {String} bank_code
 */
PayoutMethodDetailsPENBank.prototype['bank_code'] = undefined;

/**
 * @member {String} bank_account
 */
PayoutMethodDetailsPENBank.prototype['bank_account'] = undefined;

/**
 * @member {module:Model/PayoutMethodBankAccountTypeEnum} bank_account_type
 */
PayoutMethodDetailsPENBank.prototype['bank_account_type'] = undefined;






export default PayoutMethodDetailsPENBank;

