/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PayoutMethodCountryEnum.
* @enum {}
* @readonly
*/
export default class PayoutMethodCountryEnum {
    
        /**
         * value: "CI"
         * @const
         */
        "CI" = "CI";

    
        /**
         * value: "ML"
         * @const
         */
        "ML" = "ML";

    
        /**
         * value: "SN"
         * @const
         */
        "SN" = "SN";

    

    /**
    * Returns a <code>PayoutMethodCountryEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:Model/PayoutMethodCountryEnum} The enum <code>PayoutMethodCountryEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

