/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PayoutMethodTransferReasonEnum from './PayoutMethodTransferReasonEnum';

/**
 * The PayoutMethodDetailsVNDMobile model module.
 * @module Model/PayoutMethodDetailsVNDMobile
 * @version 1.37.10
 */
class PayoutMethodDetailsVNDMobile {
    /**
     * Constructs a new <code>PayoutMethodDetailsVNDMobile</code>.
     * &#x60;&#x60;&#x60;JSON \&quot;details\&quot;: {   \&quot;first_name\&quot;: \&quot;First\&quot;,   \&quot;last_name\&quot;: \&quot;Last\&quot;,   \&quot;phone_number\&quot;: \&quot;+84912345678\&quot;, // E.164 international format   \&quot;mobile_provider\&quot;: \&quot;MOMO\&quot;, // MOMO, VNPAY, VNPT, SACOMBANK, ZALOPAY   \&quot;street\&quot;: \&quot;123 Le Loi Street\&quot;,   \&quot;transfer_reason\&quot;: \&quot;personal_account\&quot; } &#x60;&#x60;&#x60;
     * @alias module:Model/PayoutMethodDetailsVNDMobile
     * @param firstName {String} 
     * @param lastName {String} 
     * @param phoneNumber {String} 
     * @param mobileProvider {String} 
     * @param street {String} 
     */
    constructor(firstName, lastName, phoneNumber, mobileProvider, street) { 
        
        PayoutMethodDetailsVNDMobile.initialize(this, firstName, lastName, phoneNumber, mobileProvider, street);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firstName, lastName, phoneNumber, mobileProvider, street) { 
        obj['first_name'] = firstName;
        obj['last_name'] = lastName;
        obj['phone_number'] = phoneNumber;
        obj['mobile_provider'] = mobileProvider;
        obj['street'] = street;
    }

    /**
     * Constructs a <code>PayoutMethodDetailsVNDMobile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/PayoutMethodDetailsVNDMobile} obj Optional instance to populate.
     * @return {module:Model/PayoutMethodDetailsVNDMobile} The populated <code>PayoutMethodDetailsVNDMobile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayoutMethodDetailsVNDMobile();

            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('phone_number')) {
                obj['phone_number'] = ApiClient.convertToType(data['phone_number'], 'String');
            }
            if (data.hasOwnProperty('mobile_provider')) {
                obj['mobile_provider'] = ApiClient.convertToType(data['mobile_provider'], 'String');
            }
            if (data.hasOwnProperty('street')) {
                obj['street'] = ApiClient.convertToType(data['street'], 'String');
            }
            if (data.hasOwnProperty('transfer_reason')) {
                obj['transfer_reason'] = PayoutMethodTransferReasonEnum.constructFromObject(data['transfer_reason']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} first_name
 */
PayoutMethodDetailsVNDMobile.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
PayoutMethodDetailsVNDMobile.prototype['last_name'] = undefined;

/**
 * @member {String} phone_number
 */
PayoutMethodDetailsVNDMobile.prototype['phone_number'] = undefined;

/**
 * @member {String} mobile_provider
 */
PayoutMethodDetailsVNDMobile.prototype['mobile_provider'] = undefined;

/**
 * @member {String} street
 */
PayoutMethodDetailsVNDMobile.prototype['street'] = undefined;

/**
 * @member {module:Model/PayoutMethodTransferReasonEnum} transfer_reason
 */
PayoutMethodDetailsVNDMobile.prototype['transfer_reason'] = undefined;






export default PayoutMethodDetailsVNDMobile;

