/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PayoutMethodIdentityCardTypeEnum from './PayoutMethodIdentityCardTypeEnum';

/**
 * The PayoutMethodDetailsCRCBank model module.
 * @module Model/PayoutMethodDetailsCRCBank
 * @version 1.37.10
 */
class PayoutMethodDetailsCRCBank {
    /**
     * Constructs a new <code>PayoutMethodDetailsCRCBank</code>.
     * &#x60;&#x60;&#x60;JSON \&quot;details\&quot;: {   \&quot;first_name\&quot;: \&quot;Andrea\&quot;,   \&quot;last_name\&quot;: \&quot;Vargas\&quot;,   \&quot;identity_card_type\&quot;: \&quot;CI\&quot;, // CI&#x3D;Cédula de identidad, CJ&#x3D;Cédula jurídica, CR&#x3D;Cédula de residencia   \&quot;identity_card_id\&quot;: \&quot;305271289\&quot;,   \&quot;iban\&quot;: \&quot;CR05015202001026284066\&quot;, // 22-char IBAN   \&quot;street\&quot;: \&quot;Calle 12, San José\&quot; } &#x60;&#x60;&#x60;
     * @alias module:Model/PayoutMethodDetailsCRCBank
     * @param firstName {String} 
     * @param lastName {String} 
     * @param identityCardType {module:Model/PayoutMethodIdentityCardTypeEnum} 
     * @param identityCardId {String} 
     * @param iban {String} 
     * @param street {String} 
     */
    constructor(firstName, lastName, identityCardType, identityCardId, iban, street) { 
        
        PayoutMethodDetailsCRCBank.initialize(this, firstName, lastName, identityCardType, identityCardId, iban, street);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firstName, lastName, identityCardType, identityCardId, iban, street) { 
        obj['first_name'] = firstName;
        obj['last_name'] = lastName;
        obj['identity_card_type'] = identityCardType;
        obj['identity_card_id'] = identityCardId;
        obj['iban'] = iban;
        obj['street'] = street;
    }

    /**
     * Constructs a <code>PayoutMethodDetailsCRCBank</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/PayoutMethodDetailsCRCBank} obj Optional instance to populate.
     * @return {module:Model/PayoutMethodDetailsCRCBank} The populated <code>PayoutMethodDetailsCRCBank</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayoutMethodDetailsCRCBank();

            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('identity_card_type')) {
                obj['identity_card_type'] = PayoutMethodIdentityCardTypeEnum.constructFromObject(data['identity_card_type']);
            }
            if (data.hasOwnProperty('identity_card_id')) {
                obj['identity_card_id'] = ApiClient.convertToType(data['identity_card_id'], 'String');
            }
            if (data.hasOwnProperty('iban')) {
                obj['iban'] = ApiClient.convertToType(data['iban'], 'String');
            }
            if (data.hasOwnProperty('street')) {
                obj['street'] = ApiClient.convertToType(data['street'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} first_name
 */
PayoutMethodDetailsCRCBank.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
PayoutMethodDetailsCRCBank.prototype['last_name'] = undefined;

/**
 * @member {module:Model/PayoutMethodIdentityCardTypeEnum} identity_card_type
 */
PayoutMethodDetailsCRCBank.prototype['identity_card_type'] = undefined;

/**
 * @member {String} identity_card_id
 */
PayoutMethodDetailsCRCBank.prototype['identity_card_id'] = undefined;

/**
 * @member {String} iban
 */
PayoutMethodDetailsCRCBank.prototype['iban'] = undefined;

/**
 * @member {String} street
 */
PayoutMethodDetailsCRCBank.prototype['street'] = undefined;






export default PayoutMethodDetailsCRCBank;

