/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PayoutMethodMobileProviderEnum.
* @enum {}
* @readonly
*/
export default class PayoutMethodMobileProviderEnum {
    
        /**
         * value: "africell"
         * @const
         */
        "africell" = "africell";

    
        /**
         * value: "airtel"
         * @const
         */
        "airtel" = "airtel";

    
        /**
         * value: "airteltigo"
         * @const
         */
        "airteltigo" = "airteltigo";

    
        /**
         * value: "emoney"
         * @const
         */
        "emoney" = "emoney";

    
        /**
         * value: "expresso"
         * @const
         */
        "expresso" = "expresso";

    
        /**
         * value: "free"
         * @const
         */
        "free" = "free";

    
        /**
         * value: "mobicash"
         * @const
         */
        "mobicash" = "mobicash";

    
        /**
         * value: "moov"
         * @const
         */
        "moov" = "moov";

    
        /**
         * value: "mpesa"
         * @const
         */
        "mpesa" = "mpesa";

    
        /**
         * value: "mtn"
         * @const
         */
        "mtn" = "mtn";

    
        /**
         * value: "orange"
         * @const
         */
        "orange" = "orange";

    
        /**
         * value: "telecom"
         * @const
         */
        "telecom" = "telecom";

    
        /**
         * value: "tigo"
         * @const
         */
        "tigo" = "tigo";

    
        /**
         * value: "tmoney"
         * @const
         */
        "tmoney" = "tmoney";

    
        /**
         * value: "vodafone"
         * @const
         */
        "vodafone" = "vodafone";

    
        /**
         * value: "wave"
         * @const
         */
        "wave" = "wave";

    

    /**
    * Returns a <code>PayoutMethodMobileProviderEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:Model/PayoutMethodMobileProviderEnum} The enum <code>PayoutMethodMobileProviderEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

