/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PayoutMethodPixKeyTypeEnum.
* @enum {}
* @readonly
*/
export default class PayoutMethodPixKeyTypeEnum {
    
        /**
         * value: "cpf"
         * @const
         */
        "cpf" = "cpf";

    
        /**
         * value: "cnpj"
         * @const
         */
        "cnpj" = "cnpj";

    
        /**
         * value: "phone"
         * @const
         */
        "phone" = "phone";

    
        /**
         * value: "email"
         * @const
         */
        "email" = "email";

    
        /**
         * value: "evp"
         * @const
         */
        "evp" = "evp";

    

    /**
    * Returns a <code>PayoutMethodPixKeyTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:Model/PayoutMethodPixKeyTypeEnum} The enum <code>PayoutMethodPixKeyTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

