/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PoliticallyExposedPerson from './PoliticallyExposedPerson';

/**
 * The PoliticallyExposedPersonResponse model module.
 * @module Model/PoliticallyExposedPersonResponse
 * @version 1.24.0
 */
class PoliticallyExposedPersonResponse {
    /**
     * Constructs a new <code>PoliticallyExposedPersonResponse</code>.
     * @alias module:Model/PoliticallyExposedPersonResponse
     */
    constructor() { 
        
        PoliticallyExposedPersonResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PoliticallyExposedPersonResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/PoliticallyExposedPersonResponse} obj Optional instance to populate.
     * @return {module:Model/PoliticallyExposedPersonResponse} The populated <code>PoliticallyExposedPersonResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PoliticallyExposedPersonResponse();

            if (data.hasOwnProperty('object')) {
                obj['object'] = PoliticallyExposedPerson.constructFromObject(data['object']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Model/PoliticallyExposedPerson} object
 */
PoliticallyExposedPersonResponse.prototype['object'] = undefined;






export default PoliticallyExposedPersonResponse;

