/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SanctionedCountry model module.
 * @module Model/SanctionedCountry
 * @version 1.25.0
 */
class SanctionedCountry {
    /**
     * Constructs a new <code>SanctionedCountry</code>.
     * @alias module:Model/SanctionedCountry
     */
    constructor() { 
        
        SanctionedCountry.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SanctionedCountry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/SanctionedCountry} obj Optional instance to populate.
     * @return {module:Model/SanctionedCountry} The populated <code>SanctionedCountry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SanctionedCountry();

            if (data.hasOwnProperty('country_name')) {
                obj['country_name'] = ApiClient.convertToType(data['country_name'], 'String');
            }
            if (data.hasOwnProperty('country_code')) {
                obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Full name of the country 
 * @member {String} country_name
 */
SanctionedCountry.prototype['country_name'] = undefined;

/**
 * Country code in 2-character alpha ISO 3166-2 country format 
 * @member {String} country_code
 */
SanctionedCountry.prototype['country_code'] = undefined;






export default SanctionedCountry;

