/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransactionReq from './TransactionReq';

/**
 * The TransactionReqRequest model module.
 * @module Model/TransactionReqRequest
 * @version 1.24.0
 */
class TransactionReqRequest {
    /**
     * Constructs a new <code>TransactionReqRequest</code>.
     * @alias module:Model/TransactionReqRequest
     */
    constructor() { 
        
        TransactionReqRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionReqRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/TransactionReqRequest} obj Optional instance to populate.
     * @return {module:Model/TransactionReqRequest} The populated <code>TransactionReqRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionReqRequest();

            if (data.hasOwnProperty('transaction_request')) {
                obj['transaction_request'] = TransactionReq.constructFromObject(data['transaction_request']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Model/TransactionReq} transaction_request
 */
TransactionReqRequest.prototype['transaction_request'] = undefined;






export default TransactionReqRequest;

