/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TransactionReqLimitsResponseObject model module.
 * @module Model/TransactionReqLimitsResponseObject
 * @version 1.24.0
 */
class TransactionReqLimitsResponseObject {
    /**
     * Constructs a new <code>TransactionReqLimitsResponseObject</code>.
     * @alias module:Model/TransactionReqLimitsResponseObject
     */
    constructor() { 
        
        TransactionReqLimitsResponseObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionReqLimitsResponseObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/TransactionReqLimitsResponseObject} obj Optional instance to populate.
     * @return {module:Model/TransactionReqLimitsResponseObject} The populated <code>TransactionReqLimitsResponseObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionReqLimitsResponseObject();

            if (data.hasOwnProperty('minimum')) {
                obj['minimum'] = ApiClient.convertToType(data['minimum'], 'Number');
            }
            if (data.hasOwnProperty('maximum')) {
                obj['maximum'] = ApiClient.convertToType(data['maximum'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The minimum limit for transaction requests (in USD)
 * @member {Number} minimum
 */
TransactionReqLimitsResponseObject.prototype['minimum'] = undefined;

/**
 * The maximum limit for transaction requests (in USD)
 * @member {Number} maximum
 */
TransactionReqLimitsResponseObject.prototype['maximum'] = undefined;






export default TransactionReqLimitsResponseObject;

