/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Document from './Document';
import Transaction from './Transaction';

/**
 * The TransactionReq model module.
 * @module Model/TransactionReq
 * @version 1.24.0
 */
class TransactionReq {
    /**
     * Constructs a new <code>TransactionReq</code>.
     * @alias module:Model/TransactionReq
     * @param content {module:Model/Transaction} 
     */
    constructor(content) { 
        
        TransactionReq.initialize(this, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content) { 
        obj['content'] = content;
    }

    /**
     * Constructs a <code>TransactionReq</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/TransactionReq} obj Optional instance to populate.
     * @return {module:Model/TransactionReq} The populated <code>TransactionReq</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionReq();

            if (data.hasOwnProperty('content')) {
                obj['content'] = Transaction.constructFromObject(data['content']);
            }
            if (data.hasOwnProperty('documents')) {
                obj['documents'] = ApiClient.convertToType(data['documents'], [Document]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('trade_id')) {
                obj['trade_id'] = ApiClient.convertToType(data['trade_id'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = Transaction.constructFromObject(data['result']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Model/Transaction} content
 */
TransactionReq.prototype['content'] = undefined;

/**
 * AML documents related to this transaction request. ```JSON \"documents\": [   {     \"id\": \"b6648ba3-1c7b-4f59-8580-684899c84a07\"   } ] ```
 * @member {Array.<module:Model/Document>} documents
 */
TransactionReq.prototype['documents'] = undefined;

/**
 * Metadata of transaction request
 * @member {Object} metadata
 */
TransactionReq.prototype['metadata'] = undefined;

/**
 * Date and time the transaction request was created
 * @member {Date} created_at
 */
TransactionReq.prototype['created_at'] = undefined;

/**
 * State of transaction request
 * @member {String} state
 */
TransactionReq.prototype['state'] = undefined;

/**
 * @member {Number} trade_id
 */
TransactionReq.prototype['trade_id'] = undefined;

/**
 * @member {String} id
 */
TransactionReq.prototype['id'] = undefined;

/**
 * @member {module:Model/Transaction} result
 */
TransactionReq.prototype['result'] = undefined;






export default TransactionReq;

