/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BankAccountDetailsResponse from '../Model/BankAccountDetailsResponse';

/**
* BankAccountDetails service.
* @module Api/BankAccountDetailsApi
* @version 1.25.0
*/
export default class BankAccountDetailsApi {

    /**
    * Constructs a new BankAccountDetailsApi. 
    * @alias module:Api/BankAccountDetailsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Fetching bank account details
     * Returns single bank account details based on the currency
     * @param {String} currency Currency of the required bank account details.  Example: &#x60;/v1/bank_account_details/NGN&#x60;
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Model/BankAccountDetailsResponse} and HTTP response
     */
    getBankAccountDetailsWithHttpInfo(currency) {
      let postBody = null;

      // verify the required parameter 'currency' is set
      if (currency === undefined || currency === null) {
        throw new Error("Missing the required parameter 'currency' when calling getBankAccountDetails");
      }


      let pathParams = {
        'Currency': currency
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AuthorizationKey', 'AuthorizationNonce', 'AuthorizationSecret', 'AuthorizationSignature'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BankAccountDetailsResponse;

      return this.apiClient.callApi(
        '/bank_account_details/{Currency}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetching bank account details
     * Returns single bank account details based on the currency
     * @param {String} currency Currency of the required bank account details.  Example: &#x60;/v1/bank_account_details/NGN&#x60;
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Model/BankAccountDetailsResponse}
     */
    getBankAccountDetails(currency) {
      return this.getBankAccountDetailsWithHttpInfo(currency)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
