/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MandateResponse from '../Model/MandateResponse';

/**
* Mandates service.
* @module Api/MandatesApi
* @version 1.37.8
*/
export default class MandatesApi {

    /**
    * Constructs a new MandatesApi. 
    * @alias module:Api/MandatesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Fetch a single mandate
     * Finds and returns a Mandate created within the current calendar year, where the mandate is linked to a Recipient owned by the authenticated API key.  Returns 404 if the mandate is not owned by the API key or was not issued in the current calendar year — mandates are only valid for the year in which they were issued.
     * @param {String} mandateID ID of the mandate.  Example: `/v1/mandates/bf9ff782-e182-45ac-abea-5bce83ad6670`
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Model/MandateResponse} and HTTP response
     */
    getMandateWithHttpInfo(mandateID) {
      let postBody = null;
      // verify the required parameter 'mandateID' is set
      if (mandateID === undefined || mandateID === null) {
        throw new Error("Missing the required parameter 'mandateID' when calling getMandate");
      }

      let pathParams = {
        'Mandate ID': mandateID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AuthorizationKey', 'AuthorizationNonce', 'AuthorizationSecret', 'AuthorizationSignature'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MandateResponse;
      return this.apiClient.callApi(
        '/mandates/{Mandate ID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Fetch a single mandate
     * Finds and returns a Mandate created within the current calendar year, where the mandate is linked to a Recipient owned by the authenticated API key.  Returns 404 if the mandate is not owned by the API key or was not issued in the current calendar year — mandates are only valid for the year in which they were issued.
     * @param {String} mandateID ID of the mandate.  Example: `/v1/mandates/bf9ff782-e182-45ac-abea-5bce83ad6670`
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Model/MandateResponse}
     */
    getMandate(mandateID) {
      return this.getMandateWithHttpInfo(mandateID)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
