/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import OpenCorporatesSearchRequest from '../Model/OpenCorporatesSearchRequest';
import OpenCorporatesSearchResponse from '../Model/OpenCorporatesSearchResponse';

/**
* OpenCorporatesCompanySearch service.
* @module Api/OpenCorporatesCompanySearchApi
* @version 1.25.0
*/
export default class OpenCorporatesCompanySearchApi {

    /**
    * Constructs a new OpenCorporatesCompanySearchApi. 
    * @alias module:Api/OpenCorporatesCompanySearchApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Search for a company on Open Corporates
     * This endpoint searches for a company on Open Corporates API and returns the name if found
     * @param {module:Model/OpenCorporatesSearchRequest} openCorporatesSearchRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Model/OpenCorporatesSearchResponse} and HTTP response
     */
    searchCompanyWithHttpInfo(openCorporatesSearchRequest) {
      let postBody = openCorporatesSearchRequest;

      // verify the required parameter 'openCorporatesSearchRequest' is set
      if (openCorporatesSearchRequest === undefined || openCorporatesSearchRequest === null) {
        throw new Error("Missing the required parameter 'openCorporatesSearchRequest' when calling searchCompany");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AuthorizationKey', 'AuthorizationNonce', 'AuthorizationSecret', 'AuthorizationSignature'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OpenCorporatesSearchResponse;

      return this.apiClient.callApi(
        '/open_corporates/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Search for a company on Open Corporates
     * This endpoint searches for a company on Open Corporates API and returns the name if found
     * @param {module:Model/OpenCorporatesSearchRequest} openCorporatesSearchRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Model/OpenCorporatesSearchResponse}
     */
    searchCompany(openCorporatesSearchRequest) {
      return this.searchCompanyWithHttpInfo(openCorporatesSearchRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
