/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import OpenCorporatesSenderUpdateRequest from '../Model/OpenCorporatesSenderUpdateRequest';
import OpenCorporatesSenderUpdateResponse from '../Model/OpenCorporatesSenderUpdateResponse';

/**
* OpenCorporatesSenderUpdate service.
* @module Api/OpenCorporatesSenderUpdateApi
* @version 1.24.0
*/
export default class OpenCorporatesSenderUpdateApi {

    /**
    * Constructs a new OpenCorporatesSenderUpdateApi. 
    * @alias module:Api/OpenCorporatesSenderUpdateApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Update Sender with data retrieved from Open Corporates
     * This endpoint searches for a company on Open Corporates API and updates the associated Sender fields with the search results
     * @param {module:Model/OpenCorporatesSenderUpdateRequest} openCorporatesSenderUpdateRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Model/OpenCorporatesSenderUpdateResponse} and HTTP response
     */
    updateSenderWithHttpInfo(openCorporatesSenderUpdateRequest) {
      let postBody = openCorporatesSenderUpdateRequest;

      // verify the required parameter 'openCorporatesSenderUpdateRequest' is set
      if (openCorporatesSenderUpdateRequest === undefined || openCorporatesSenderUpdateRequest === null) {
        throw new Error("Missing the required parameter 'openCorporatesSenderUpdateRequest' when calling updateSender");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['AuthorizationKey', 'AuthorizationNonce', 'AuthorizationSecret', 'AuthorizationSignature'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OpenCorporatesSenderUpdateResponse;

      return this.apiClient.callApi(
        '/open_corporates/update_sender', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Update Sender with data retrieved from Open Corporates
     * This endpoint searches for a company on Open Corporates API and updates the associated Sender fields with the search results
     * @param {module:Model/OpenCorporatesSenderUpdateRequest} openCorporatesSenderUpdateRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Model/OpenCorporatesSenderUpdateResponse}
     */
    updateSender(openCorporatesSenderUpdateRequest) {
      return this.updateSenderWithHttpInfo(openCorporatesSenderUpdateRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
