/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferzeroSdk);
  }
}(this, function(expect, TransferzeroSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferzeroSdk.DlocalBalance();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DlocalBalance', function() {
    it('should create an instance of DlocalBalance', function() {
      // uncomment below and update the code to test DlocalBalance
      //var instane = new TransferzeroSdk.DlocalBalance();
      //expect(instance).to.be.a(TransferzeroSdk.DlocalBalance);
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new TransferzeroSdk.DlocalBalance();
      //expect(instance).to.be();
    });

    it('should have the property availableBalance (base name: "available_balance")', function() {
      // uncomment below and update the code to test the property availableBalance
      //var instance = new TransferzeroSdk.DlocalBalance();
      //expect(instance).to.be();
    });

    it('should have the property previousDayClosingBalance (base name: "previous_day_closing_balance")', function() {
      // uncomment below and update the code to test the property previousDayClosingBalance
      //var instance = new TransferzeroSdk.DlocalBalance();
      //expect(instance).to.be();
    });

    it('should have the property currentBalanceDate (base name: "current_balance_date")', function() {
      // uncomment below and update the code to test the property currentBalanceDate
      //var instance = new TransferzeroSdk.DlocalBalance();
      //expect(instance).to.be();
    });

  });

}));
