/**
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferzeroSdk);
  }
}(this, function(expect, TransferzeroSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferzeroSdk.EntityUpdateRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EntityUpdateRequest', function() {
    it('should create an instance of EntityUpdateRequest', function() {
      // uncomment below and update the code to test EntityUpdateRequest
      //var instane = new TransferzeroSdk.EntityUpdateRequest();
      //expect(instance).to.be.a(TransferzeroSdk.EntityUpdateRequest);
    });

    it('should have the property entityId (base name: "entity_id")', function() {
      // uncomment below and update the code to test the property entityId
      //var instane = new TransferzeroSdk.EntityUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property entityType (base name: "entity_type")', function() {
      // uncomment below and update the code to test the property entityType
      //var instane = new TransferzeroSdk.EntityUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property manualFields (base name: "manual_fields")', function() {
      // uncomment below and update the code to test the property manualFields
      //var instane = new TransferzeroSdk.EntityUpdateRequest();
      //expect(instance).to.be();
    });

  });

}));
