/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferzeroSdk);
  }
}(this, function(expect, TransferzeroSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferzeroSdk.PayoutMethodDetailsCRCBank();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PayoutMethodDetailsCRCBank', function() {
    it('should create an instance of PayoutMethodDetailsCRCBank', function() {
      // uncomment below and update the code to test PayoutMethodDetailsCRCBank
      //var instane = new TransferzeroSdk.PayoutMethodDetailsCRCBank();
      //expect(instance).to.be.a(TransferzeroSdk.PayoutMethodDetailsCRCBank);
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new TransferzeroSdk.PayoutMethodDetailsCRCBank();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new TransferzeroSdk.PayoutMethodDetailsCRCBank();
      //expect(instance).to.be();
    });

    it('should have the property identityCardType (base name: "identity_card_type")', function() {
      // uncomment below and update the code to test the property identityCardType
      //var instance = new TransferzeroSdk.PayoutMethodDetailsCRCBank();
      //expect(instance).to.be();
    });

    it('should have the property identityCardId (base name: "identity_card_id")', function() {
      // uncomment below and update the code to test the property identityCardId
      //var instance = new TransferzeroSdk.PayoutMethodDetailsCRCBank();
      //expect(instance).to.be();
    });

    it('should have the property iban (base name: "iban")', function() {
      // uncomment below and update the code to test the property iban
      //var instance = new TransferzeroSdk.PayoutMethodDetailsCRCBank();
      //expect(instance).to.be();
    });

    it('should have the property street (base name: "street")', function() {
      // uncomment below and update the code to test the property street
      //var instance = new TransferzeroSdk.PayoutMethodDetailsCRCBank();
      //expect(instance).to.be();
    });

  });

}));
