/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferzeroSdk);
  }
}(this, function(expect, TransferzeroSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferzeroSdk.PayoutMethodDetailsZARBank();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PayoutMethodDetailsZARBank', function() {
    it('should create an instance of PayoutMethodDetailsZARBank', function() {
      // uncomment below and update the code to test PayoutMethodDetailsZARBank
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be.a(TransferzeroSdk.PayoutMethodDetailsZARBank);
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property street (base name: "street")', function() {
      // uncomment below and update the code to test the property street
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postal_code")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property bankCode (base name: "bank_code")', function() {
      // uncomment below and update the code to test the property bankCode
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property bankAccount (base name: "bank_account")', function() {
      // uncomment below and update the code to test the property bankAccount
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumber (base name: "phone_number")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property transferReasonCode (base name: "transfer_reason_code")', function() {
      // uncomment below and update the code to test the property transferReasonCode
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property transferReason (base name: "transfer_reason")', function() {
      // uncomment below and update the code to test the property transferReason
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property contactFirstName (base name: "contact_first_name")', function() {
      // uncomment below and update the code to test the property contactFirstName
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property contactLastName (base name: "contact_last_name")', function() {
      // uncomment below and update the code to test the property contactLastName
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property registrationNumber (base name: "registration_number")', function() {
      // uncomment below and update the code to test the property registrationNumber
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property natureOfBusiness (base name: "nature_of_business")', function() {
      // uncomment below and update the code to test the property natureOfBusiness
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

    it('should have the property legalEntityType (base name: "legal_entity_type")', function() {
      // uncomment below and update the code to test the property legalEntityType
      //var instane = new TransferzeroSdk.PayoutMethodDetailsZARBank();
      //expect(instance).to.be();
    });

  });

}));
