/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferzeroSdk);
  }
}(this, function(expect, TransferzeroSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferzeroSdk.Sender();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Sender', function() {
    it('should create an instance of Sender', function() {
      // uncomment below and update the code to test Sender
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be.a(TransferzeroSdk.Sender);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property street (base name: "street")', function() {
      // uncomment below and update the code to test the property street
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postal_code")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property phoneCountry (base name: "phone_country")', function() {
      // uncomment below and update the code to test the property phoneCountry
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumber (base name: "phone_number")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property ip (base name: "ip")', function() {
      // uncomment below and update the code to test the property ip
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property addressDescription (base name: "address_description")', function() {
      // uncomment below and update the code to test the property addressDescription
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property identificationNumber (base name: "identification_number")', function() {
      // uncomment below and update the code to test the property identificationNumber
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property identificationType (base name: "identification_type")', function() {
      // uncomment below and update the code to test the property identificationType
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property lang (base name: "lang")', function() {
      // uncomment below and update the code to test the property lang
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property middleName (base name: "middle_name")', function() {
      // uncomment below and update the code to test the property middleName
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property birthDate (base name: "birth_date")', function() {
      // uncomment below and update the code to test the property birthDate
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property occupation (base name: "occupation")', function() {
      // uncomment below and update the code to test the property occupation
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property nationality (base name: "nationality")', function() {
      // uncomment below and update the code to test the property nationality
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property legalEntityType (base name: "legal_entity_type")', function() {
      // uncomment below and update the code to test the property legalEntityType
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property registrationDate (base name: "registration_date")', function() {
      // uncomment below and update the code to test the property registrationDate
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property registrationNumber (base name: "registration_number")', function() {
      // uncomment below and update the code to test the property registrationNumber
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property natureOfBusiness (base name: "nature_of_business")', function() {
      // uncomment below and update the code to test the property natureOfBusiness
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property sourceOfFunds (base name: "source_of_funds")', function() {
      // uncomment below and update the code to test the property sourceOfFunds
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property customSourceOfFunds (base name: "custom_source_of_funds")', function() {
      // uncomment below and update the code to test the property customSourceOfFunds
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property coreBusinessActivity (base name: "core_business_activity")', function() {
      // uncomment below and update the code to test the property coreBusinessActivity
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property purposeOfOpeningAccount (base name: "purpose_of_opening_account")', function() {
      // uncomment below and update the code to test the property purposeOfOpeningAccount
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property officePhone (base name: "office_phone")', function() {
      // uncomment below and update the code to test the property officePhone
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property vatRegistrationNumber (base name: "vat_registration_number")', function() {
      // uncomment below and update the code to test the property vatRegistrationNumber
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property financialRegulator (base name: "financial_regulator")', function() {
      // uncomment below and update the code to test the property financialRegulator
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property regulatoryLicenceNumber (base name: "regulatory_licence_number")', function() {
      // uncomment below and update the code to test the property regulatoryLicenceNumber
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property contactPersonEmail (base name: "contact_person_email")', function() {
      // uncomment below and update the code to test the property contactPersonEmail
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property tradingCountry (base name: "trading_country")', function() {
      // uncomment below and update the code to test the property tradingCountry
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property tradingAddress (base name: "trading_address")', function() {
      // uncomment below and update the code to test the property tradingAddress
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property tradingName (base name: "trading_name")', function() {
      // uncomment below and update the code to test the property tradingName
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property numberMonthlyTransactions (base name: "number_monthly_transactions")', function() {
      // uncomment below and update the code to test the property numberMonthlyTransactions
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property amountMonthlyTransactions (base name: "amount_monthly_transactions")', function() {
      // uncomment below and update the code to test the property amountMonthlyTransactions
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property documents (base name: "documents")', function() {
      // uncomment below and update the code to test the property documents
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property errors (base name: "errors")', function() {
      // uncomment below and update the code to test the property errors
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property onboardingStatus (base name: "onboarding_status")', function() {
      // uncomment below and update the code to test the property onboardingStatus
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property politicallyExposedPeople (base name: "politically_exposed_people")', function() {
      // uncomment below and update the code to test the property politicallyExposedPeople
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property externalId (base name: "external_id")', function() {
      // uncomment below and update the code to test the property externalId
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property cityOfBirth (base name: "city_of_birth")', function() {
      // uncomment below and update the code to test the property cityOfBirth
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property countryOfBirth (base name: "country_of_birth")', function() {
      // uncomment below and update the code to test the property countryOfBirth
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property salesLeadId (base name: "sales_lead_id")', function() {
      // uncomment below and update the code to test the property salesLeadId
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new TransferzeroSdk.Sender();
      //expect(instance).to.be();
    });

  });

}));
